## Adapted from:
## https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html

- hosts: localhost
  gather_facts: yes

  vars:
    - my_name: "drivers_nvidia_container"
    - my_deb_prereq:
      - gpg
      - aria2
      - ca-certificates
    - my_deb_nvidia:
      - nvidia-container-toolkit

  tasks:

  - name: "{{ my_name }} install prereqs"
    ansible.builtin.apt:
       name: "{{ my_deb_prereq }}"
       state: latest
    when: ansible_distribution == "Ubuntu" or
          ansible_distribution == "Debian"

  - name: "{{ my_name }} install nvidia container toolkit"
    ansible.builtin.apt:
      name: "{{ my_deb_nvidia }}"
      state: latest
      update_cache: true
    notify: "{{ my_name }} restart service"
    when: ansible_distribution == "Ubuntu" or
          ansible_distribution == "Debian"

  - name: "{{ my_name }} change default docker runtime to nvidia"
    ansible.builtin.command: /usr/bin/nvidia-ctk runtime configure --runtime docker --nvidia-set-as-default
    notify: "{{ my_name }} restart service"

  handlers:

  - name: "{{ my_name }} update apt"
    ansible.builtin.apt:
      update_cache: true
    when: ansible_distribution == "Ubuntu" or
          ansible_distribution == "Debian"

  - name: "{{ my_name }} restart service"
    ansible.builtin.service:
      name: docker
      state: restarted
